# a=int(input('enter a value: '))
# if(a%3==0 and a%5==0):
#     print('yes')

#!-------IF-ELSE------
# a=int(input('enter a value:'))
# if(a%2==0):
#     print('square:',a**2)
# else:
#     print('cube:',a**3)

#!----ELIF----
# a=input('enter:')
# if 'a'<=a<='z':
#     print(f'{a} is lowercase')
# elif 'A'<=a<='Z':
#     print(f'{a} is uppercase')
# elif '0'<=a<='9':
#     print(f'{a} is number')
# else:
#     print(f'{a} is special charcater')

# print(type(a))

# print(chr(89))
# print(ord("a"))


