# ------------------------------------------------------------
# nput_output
# ------------------------------------------------------------

name = input("Enter your name: ")

print("Hello", name)


# ------------------------------------------------------------
# Print_function
# ------------------------------------------------------------

print("Python")
print("Data Science")

print("Python", "Data", "Science")

print("Python", end=" ")
print("Programming")


# ------------------------------------------------------------
#  formatting
# ------------------------------------------------------------

name = "Gopi"
age = 22
percentage = 87.5678

print("Name:", name)
print("Age:", age)

print(f"Name: {name}")
print(f"Age: {age}")
print(f"Percentage: {percentage:.2f}")


# ------------------------------------------------------------
#escape_sequences
# ------------------------------------------------------------

print("Hello\nWorld")
print("Python\tProgramming")
print("He said \"Hello\"")
print("Python\\Programming")
