# arithmetic_operators
# ------------------------------------------------------------

a = 10
b = 3

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)
print("Floor Division:", a // b)
print("Modulus:", a % b)
print("Power:", a ** b)


# ------------------------------------------------------------
# assignment_operators
# ------------------------------------------------------------

a = 10

a += 5
print(a)

a -= 2
print(a)

a *= 2
print(a)

a /= 2
print(a)

a //= 2
print(a)

a %= 3
print(a)

a **= 2
print(a)


# ------------------------------------------------------------
#comparison_operators
# ------------------------------------------------------------

a = 10
b = 20

print(a == b)
print(a != b)
print(a > b)
print(a < b)
print(a >= b)
print(a <= b)
